version: '3.7'
services:
  server:
    container_name: orders-test-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
    environment:
      - FLASK_APP=orders.py
      - FLASK_ENV=development
